name: Pipeline CI/CD

on:
    push:
        branches:
          - mai

permissions:
  id-token: write
  contents: read

jobs:
  job1:
    name: Terraform 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v6.1.0  
        with:
          role-to-assume: arn:aws:iam::149729185352:role/GitHubInfraRole
          aws-region: us-east-2
      
      - name: Login ECR
        uses: aws-actions/amazon-ecr-login@v2.3.0

      - name: Build Image
        run: docker build -t repositorio-website-lab-devops:v1.0 .
          docker tag repositorio-website-lab-devops:v1.0 149729185352.dkr.ecr.us-east-2.amazonaws.com/site-prod:v1.0
          docker push 149729185352.dkr.ecr.us-east-2.amazonaws.com/site-prod:v1.0